### ISSUE TITLE
Consider requiring browser-request for node-browserify 

### ISSUE THREAD

**Issue by xaviervalarino** [JeffResc/TinyURL-Node.js#1]
Have you considered requiring [browser-request](https://github.com/iriscouch/browser-request) along with (or, conditionally, instead of ) [request](https://github.com/request/request) so that this module can be bundled with [browserify](https://github.com/substack/node-browserify)?

**Comment by ghost** [comment]
Due to a [recent PR](https://github.com/AlphaT3ch/TinyURL/pull/2) by @piranna I have decided to close this Issue as it is no longer relevant.
