### ISSUE TITLE
Unexpected token >

### ISSUE THREAD

**Issue by vedantkarande93** [JeffResc/TinyURL-Node.js#10]
vedantkarande93 changed the title from When i install this npm in centos it is not working. It gives me err like "Unexpected token >" and if I installed this npm in Ubuntu then it is properly running to Unexpected token >

**Comment by vedantkarande93** [comment]
When i install this npm in centos it is not working. It gives me err like "Unexpected token >" and if I installed this npm in Ubuntu then it is properly running

**Comment by rayarikar** [comment]
There is no need of token to make the call to tiny url service. Its a web hosted service open to anyone
