### ISSUE TITLE
TinyUrl for angular 6 is not supporting

### ISSUE THREAD

**Issue by faridaanjum** [JeffResc/TinyURL-Node.js#12]
When I want to use it in my application of angular 6 it is throwing an error like 
  ERROR in ./node_modules/tinyurl/index.js
 Module not found: Error: Can't resolve 'http' in 'C:\Users\Farida\git\ppms_angular6\ppms-root\app\ppms- 
 ui\ui\node_modules\tinyurl'

**Comment by JeffResc** [comment]
Please ensure you have the HTTP module installed on your system before attempting to use TinyURL. If you feel that this is an error in the software, please submit another issue via GitHub.
