### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource - issue

### ISSUE THREAD

**Issue by cvinothkumar** [JeffResc/TinyURL-Node.js#13]
Failed to load http://tinyurl.com/api-create.php?url=http%3A%2F%2Fgoogle.com: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'my local host' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by andrevenancio** [comment]
Same here. Is the library discontinued?

**Comment by tskravisankar** [comment]
I'm also facing this issue. Can someone help me to resolve it?

![image](https://user-images.githubusercontent.com/26854917/70911221-6c456a00-2037-11ea-982f-b57af9da491d.png)

**Comment by gabyvlad96** [comment]
Is someone working on this issue?
I have the same problem

**Comment by SethuSenthil** [comment]
This is not really an issue with the library but a web standard. You can not run this on the client-side (unless you enable no-cores mode which is not idle for most situations), you will need to run this library on a server-side instance.

**Comment by JeffResc** [comment]
Closed, please refer to @SethuSenthil's response.
