### ISSUE TITLE
Add support for the alias function

### ISSUE THREAD

**Issue by JeffResc** [JeffResc/TinyURL-Node.js#17]
TinyURL supports adding aliases to your URL ([more on this here](https://tinyurl.com/)). For this issue, a function will need to be created that will allow users to add an alias when creating a short URL. The function should also return an error if that alias is already in use. For information on how the TinyURL API works with aliases, I'd recommend reading [this question](https://stackoverflow.com/questions/22919505/syntax-for-tinyurl-custom-alias) on StackOverflow. Please reply if you'd like to be assigned to this issue.

**Comment by JoshLambertUW** [comment]
I'll take on this one.
