### ISSUE TITLE
Add support to resolve a URL

### ISSUE THREAD

**Issue by JeffResc** [JeffResc/TinyURL-Node.js#18]
Add support to resolve a URL. This function should allow the user to input a TinyURL and return the expanded form of that URL. [Here's an example of how it's done in Python](https://taoofmac.com/space/blog/2009/08/10/2205), but it will need to be ported to JavaScript/Node.js for this project. Please reply if you'd like to be assigned to this issue.

**Comment by ahmedkrmn** [comment]
Can I work on this one?
