### ISSUE TITLE
Rely on No Dependencies

### ISSUE THREAD

**Issue by ghost** [JeffResc/TinyURL-Node.js#5]
Currently the project relies on the request dependence which can install a lot of unnecessary code and waste a small amount of time while downloading. This is a limitation of this package.

**Comment by ynrstp** [comment]
Hi @AlphaT3ch, have you looked at the following package? [Needle](https://www.npmjs.com/package/needle). It only has 2 dependencies, in comparison to the 21 of Request.

I can also rewrite it for you using Needle if you're interested!

**Comment by ghost** [comment]
Thanks @ynrstp that's great! If you're interested in submitting a PR, go ahead, but if you don't want to I'd also be happy to do it myself.

If you need PRs for Hacktoberfest, I've opened the same issue on my [is.gd](https://github.com/AlphaT3ch/Is.gd) and [V.gd](https://github.com/AlphaT3ch/V.gd) repositories. But again, if you're not interested I will happly implement it myself. Thanks again! :)

Edit: I've also applied the same issue to my [Notifico-NPM](https://github.com/AlphaT3ch/Notifico-NPM). It's a really simple package and if you're interested it'll need to be done there too.

**Comment by ynrstp** [comment]
Hey @AlphaT3ch  I just made a PR for the TinyUrl repo. If you're happy with it I can also do it for the other repos :)
