### ISSUE TITLE
Sudden No 'Access-Control-Allow-Origin' error

### ISSUE THREAD

**Issue by christopheSeeka** [JeffResc/TinyURL-Node.js#70]
Hello,

I'm using the lib since a while but suddenly today I'm getting the following error:

_No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

Is it a new change in cors policy on tinyurl side? Any workaround?

**Comment by yuchinchenTW** [comment]
I think the api is dead I use it today and found out
![image](https://user-images.githubusercontent.com/54444432/142362706-5067af41-7dfa-4391-8639-f6131bf9635c.png)

I try in diff Saas online service but all have same error

**Comment by toraghulravi** [comment]
+1

**Comment by sicadev** [comment]
My guess is Tinyurl dropped the publicly accessible get endpoint and now require athentication token access, through api.tinyurl.com/create post request :/

**Comment by yuchinchenTW** [comment]
I mean if you guys know any other free options?

**Comment by coolshatul** [comment]
> My guess is Tinyurl dropped the publicly accessible get endpoint and now require athentication token access, through api.tinyurl.com/create post request :/

yes! they added some security in there API, able to shorten URL using browser but not using postman or code 

![image](https://user-images.githubusercontent.com/3442247/142367755-c6388c69-4ba1-4137-8292-ac0cd88ac322.png)

**Comment by yuchinchenTW** [comment]
can this be fixed?

**Comment by rvshah512** [comment]
+1

**Comment by pgicharu** [comment]
+1 
Experiencing this as well. Their free plan has unlimited shortened urls so we will still be using tinyurl as it suites our use case. Maybe adopting the library to add the token as a param would be the way to go.

**Comment by Aravindh-SNR** [comment]
@pgicharu Any idea about the API limit in their free plan? I'm able to hit the API with a free plan token, but their Plan info says there's no API access in free plan (they've written a dash '-' for API limit)

**Comment by coolshatul** [comment]
> can this be fixed?

using below code for now..

`
const axios = require('axios');

exports.shorten = async (url) => {
  try {
    return axios.post('https://api.tinyurl.com/create?api_token=' + process.env.api_token, { "url": url })
  } catch (error) {
    throw error;
  }
}

`

**Comment by pgicharu** [comment]
> @pgicharu Any idea about the API limit in their free plan? I'm able to hit the API with a free plan token, but their Plan info says there's no API access in free plan (they've written a dash '-' for API limit)

Hi @Aravindh-SNR , sorry I took long to reply. Reached out to TinyURL support team to enquire about the same. The API limit for the free plan is currently set to 500.

**Comment by sicadev** [comment]
> > @pgicharu Any idea about the API limit in their free plan? I'm able to hit the API with a free plan token, but their Plan info says there's no API access in free plan (they've written a dash '-' for API limit)
> 
> Hi @Aravindh-SNR , sorry I took long to reply. Reached out to TinyURL support team to enquire about the same. The API limit for the free plan is currently set to 500.

Per month?

**Comment by pgicharu** [comment]
> Per month?

I believe so. I have asked for clarification though, will report back once they reply 👍🏾

**Comment by Aravindh-SNR** [comment]
@pgicharu thank you :)

**Comment by pgicharu** [comment]
I can confirm, the API limit in their free plan is currently set to 500 per month.
