### ISSUE TITLE
Failure using the service

### ISSUE THREAD

**Issue by omeriko** [JeffResc/TinyURL-Node.js#71]
Hi 
We've installed the tinyurl package from npm about a year ago in our NodeJS application running on aws in order to shorten our automatically generated long urls and it's been working great for us

From this morning we've been getting errors when trying to use the service. instead on getting a shortened url the TinyURL.shorten(longUrl) function returns the following response:

"<!DOCTYPE HTML>\n<html lang=\"en-US\">\n<head>\n <meta charset=\"UTF-8\" />\n <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\" />\n <meta name=\"robots\" content=\"noindex, nofollow\" />\n <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n <title>Just a moment...</title>\n <style type=\"text/css\">\n html, body {width: 100%; height: 100%; margin: 0; padding: 0;}\n body {background-color"

What is the reason for that failure?

**Comment by saisanthosh23** [comment]
> Hi We've installed the tinyurl package from npm about a year ago in our NodeJS application running on aws in order to shorten our automatically generated long urls and it's been working great for us
> 
> From this morning we've been getting errors when trying to use the service. instead on getting a shortened url the TinyURL.shorten(longUrl) function returns the following response:
> 
> "\n<html lang="en-US">\n\n <meta charset="UTF-8" />\n <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />\n <meta name="robots" content="noindex, nofollow" />\n <meta name="viewport" content="width=device-width,initial-scale=1" />\n <title>Just a moment...</title>\n <style type="text/css">\n html, body {width: 100%; height: 100%; margin: 0; padding: 0;}\n body {background-color"
> 
> What is the reason for that failure?

**I'm also facing the same.
Kindly provide solution asap**

**Comment by namavamshi** [comment]
> > Hi We've installed the tinyurl package from npm about a year ago in our NodeJS application running on aws in order to shorten our automatically generated long urls and it's been working great for us
> > From this morning we've been getting errors when trying to use the service. instead on getting a shortened url the TinyURL.shorten(longUrl) function returns the following response:
> > "\n\n\n \n \n \n \n \n <title>Just a moment...</title>\n <style type="text/css">\n html, body {width: 100%; height: 100%; margin: 0; padding: 0;}\n body {background-color"
> > What is the reason for that failure?
> 
> **I'm also facing the same. Kindly provide solution asap**

Downgrading the version to 1.1.6 worked for me

**Comment by mpro-madhu** [comment]
We observed this in our application too. yesterday and once couple of months ago 

Strange thing is, when it happened for first time, the shorten call would result in error. So we defined fall back mechanism to use original url.

But when it happened yesterday, the call was success and yet to result was having HTML content as reported by @omeriko . which made it even tricky to define fall back mechanism. 

Is there any load consideration we should be aware of ?

**Comment by omeriko** [comment]
Today we received from TinyURL's technical support the following reply on that issue: 

> You were probably using an old deprecated API endpoint, which was affected by the DDoS attack that hit us yesterday. You should switch to the newer API documented here: https://api.tinyurl.com 
> 
> The rule that mitigated it on our web application firewall applied a challenge to our site and ended up including the old API endpoint, but it did not affect our supported API.
